---
id: themes-hochschule
name: themes-hochschule
full: Horde Hochschule Theme
description: >-
  This Hochschule theme is based on the horde default theme.
  It contains some basic modifications as used by some German highschools
  http://www.horde.org.
list: ~
type: horde-theme
homepage: https://www.horde.org/apps/horde
authors:
  -
    name: Ralf Lang
    user: rlang
    email: lang@b1-systems.de
    active: true
    role: lead
version:
  release: 1.0.0
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2
  uri: http://www.horde.org/licenses/lgpl
dependencies:
  required:
    php: ^7
    composer:
      horde/horde: '*'
